import 'package:flutter/material.dart';

class TermsAndConditions extends StatefulWidget {

  @override
  State<TermsAndConditions> createState() => _TermsAndConditionsState();
}

class _TermsAndConditionsState extends State<TermsAndConditions> {
  @override
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        title: const Text(
          "Termini e Condizioni",
          style: TextStyle(
            color: Colors.white,
          ),
        ),
        leading: IconButton(
          icon: const Icon(Icons.close),
          color: Colors.white,
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
      body:SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            children: const [


              SizedBox(height:20,),
              Text(
                "Le applicazioni mobile “Drivehome” e “Autisti Drivehome”, di proprietà di Simone Demichele (CF: DMCSMN97T09L328T) residente in via Zara 8 ,San Ferdinando di Puglia, compongono la piattaforma di servizi, il cui dettaglio viene successivamente descritto (da ora in poi “Drivehome”,“Autisti Drivehome”, l’ “applicazione” o la “piattaforma”), rivolta sia a persone fisiche, che a persone giuridiche. L’applicazione Drivehome è scaricabile e visibile in chiaro da qualsiasi soggetto, da ora in poi “visitatore”, fino alle pagine di Registrazione di un account e di Accesso. Il visitatore può accedere inoltre alle seguenti pagine, che sono pubblicate in chiaro: Privacy Policy e  Termini e Condizioni. In nessun caso e per nessuna ragione, il visitatore qualora non riuscisse ad entrare in contatto con Drivehome, può chiedere rimborsi per eventuali costi per contattare la piattaforma sostenuti a seguito di malfunzionamenti attribuibili a problemi di connessione ascrivibili ai nostri fornitori. Questa condizione di non esigibilità vale sia per Dreivehome stessa che per tutta la filiera di fornitori e/o collaboratori continuativi e/o occasionali."
                    "Drivehome offre due distinte tipologie di servizio a due distinti tipi di utenti, clienti ed autisti o driver, definiti come segue. I clienti sono persone sia fisiche che giuridiche che cercano prestatori d’opera per la guida della propria auto, quindi autisti occasionali. Gli autisti o driver (d’ora in poi o “autisti” o “driver”) sono soggetti che, avendone i requisiti, stabiliti da Drivehome unilateralmente e senza alcuna possibilità di negoziazione alcuna da parte dei soggetti che richiedono, offrono il proprio tempo per guidare auto altrui. Il cliente si definisce tale quando dopo aver cliccato da visitatore sul bottone “Registrati” , compila correttamente e completamente il form di registrazione. Il form prevede l’inserimento dei seguenti dati: Nome, Cognome, E-mail (valida come username), Password, N. telefono.  A questo punto il “visitatore” dopo aver cliccato su  “Registrati” dichiara di aver letto e accettato l’ Informativa sulla privacy e i Termini e Condizioni di Utilizzo dell’applicazione, inquanto, nella stessa pagina di Registrazione si può leggere: “Registrando un account, accetti i nostri Termini e condizioni e Informativa sulla privacy”. "
                    "Apparirà quindi una finestra pop-up con messaggio “Verifica email. Devi verificare la tua email prima di accedere. Controlla la tua email”. La mail avrà come oggetto “Benvenuto su Drivehome!” ed all’interno del testo ci sarà il link per attivare l’utenza. Il futuro cliente è tenuto, qualora non vedesse la mail a controllare anche la cartella della posta indesiderata. Una volta cliccato sul link si aprirà una pagina web con la scritta “Il tuo account è stato attivato” e tornando sull’app avrà quindi portato a termine la Registrazione."
                    "A questo punto il cliente è loggato e potrà ottenere in modo gratuito info di costo/tempo sui viaggi. Dovrà semplicemente concedere l’autorizzazione alla geolocalizzazione del dispositivo in uso e inserire il luogo di destinazione desiderato all’interno del nuovo form all’interno della nuova pagina con mappa GoogleMaps. Continuando nella navigazione, dopo aver cliccato il pulsante “Richiedi un Autista”, potrà vedere nella schermata successiva l’elenco di autisti registrati, abilitati e disponibili a trenta chilometri di distanza , su base Google Maps, dal luogo di partenza identificato automaticamente dall’applicazione e i relativi nome, durata del viaggio per l’arrivo a luogo di destinazione inserito nel form, prezzo ipotetico preventivato e n^ di stelle che è un indicatore di qualità dell’autista, la cui spiegazione è fornita in seguito, e prenotare cliccando la card dell’autista desiderato."
                    "Cliccando sulla card, il cliente atterra sulla pagina con il riepilogo del percorso di strada da percorrere disegnato direttamente sulla mappa di Google Maps, in attesa che l’autista accetti la richiesta appena inviata sottoforma di notifica push. A questo punto al cliente apparirà una schermata con il seguente testo: “Richiesta inviata. Attendere..” e poi “RICORDATI CHE DEVI AVERE UN AUTO DA FARE GUIDARE.” e anche “CONTROLLA L'ASSICURAZIONE!”. Una volta che il driver avrà accettato e durante tutta la durata del servizio e nei tempi di attesa, il cliente potrà visualizzare nella schermata dell’applicazione gli stati della corsa con messaggi che cambieranno in base allo stato della corsa. Ad esempio: quando il driver starà arrivando, il cliente vedrà il messaggio “Il tuo autista arriverà in 20 minuti”; quando il driver sarà arrivato, vedrà “Il tuo autista è arrivato!”; una volta partiti, vedrà “Arrivo a destinazione in 20 minuti”. Una volta arrivati a destinazione e terminata la corsa, verrà visualizzato un popup con prezzo da pagare al driver in contanti e successivamente un altro popup con cui il cliente potrà recensire il servizio ricevuto dal driver."
                    "Il prezzo e/o la eventuale rideterminazione dello stesso mostrato al termine della corsa e nel momento di scelta del driver da parte del cliente è fatto in nome e per conto del driver come puro esempio di retribuzione per servizi “one shot”. Il cliente è libero di accettare o rifiutare il prezzo e/o la eventuale rideterminazione. Il cliente è libero di scegliere un prezzo che ritiene adeguato al servizio offerto. Non esiste nussun fee piattaforma dovuto dal cliente o dal driver al momento del pagamento, inquanto Drivehome si pone come piattaforma no-profit. La piattaforma da disponibilità a poter contattare il driver durante l’utilizzo dell’applicazione via chiamata telefonica e/o via piattaforme di messaggistica, quale a titolo meramente esemplificativo Whatsapp. Tra cliente e Drivehome non si instaura nessun “contratto”, difatti, il cliente può chiudere in qualsiasi momento l’applicazione e/o annullare le richieste di autisti privati in corso, cliccando in alto a sinistra sul pulsante “x”, senza dover corrispondere alla piattaforma nessuna somma di denaro, né tantomeno all’autista ne tantomeno il driver deve alcuna fee all’applicazione per il suo utilizzo o per i servizi offerti."
                    "Drivehome declina formalmente qualsiasi responsabilità in merito al rilascio di fatture o ricevute da parte dei driver a conclusione del servizio offerto al cliente. Spetterà al driver, a conclusione del servizio e arrivo a destinazione impostato dal cliente, rilasciare una fattura in caso di persona giuridica o una ricevuta per prestazione occasionale in caso di persona fisica. Drivehome non è in alcun modo responsabile per eventuali danni diretti, indiretti, incidentali, consequenziali, punitivi o esemplari, nonché per eventuali perdite di guadagno derivanti da qualsiasi violazione dei termini da parte dei clienti o dei driver."
                    "Non c’è peraltro nessun obbligo da parte di Drivehome di rispondere al cliente in qualsivoglia momento del servizio scambiatosi tra le parti. Nel momento in cui il cliente sceglie un driver e il driver scelto o altro driver accetta, l’obbligo di Drivehome si perfeziona fornendo al cliente il nominativo del driver disponibile e al driver l’indirizzo di partenza del cliente, cessando nello stesso momento qualsiasi altro obbligo. Una volta che il contatto e l’indirizzo di partenza sono stati forniti, cessando qualsiasi obbligazione di Drivehome è tutto in capo ai due soggetti cliente ed autista che sono gli attori del servizio offerto dall’autista al cliente."
                    "Qualora un cliente persona giuridica non volesse avere il servizio erogato a fronte di una prestazione occasionale tra privato ed azienda, ma necessitasse fattura Drivehome fatturerebbe al cliente una cifra stabilita con una trattativa ad hoc e basata su un Listino aziende richiedibile in qualsiasi momento. Per questo tipo di servizio l’azienda contraente si fa carico di qualsiasi danno provocato a cose e/o persone dal driver sia per dolo, preterintenzione o colpa riservandosi di adire le vie legali contro il driver. Il pagamento della fattura è anticipato e qualora il credito non fosse usato entro l’anno solare si trasforma in penale. L’azienda non potrà in alcun modo rivalersi su Drivehome per danni di qualsiasi genere causati anche per colpa del driver, ma dovrà verificare che per tutte le fattispecie di danni stessi dovuti alla guida di un terzo siano presenti assicurazioni stipulate dalla azienda stessa, su veicoli cose o persone."
                    "La piattaforma Autisti Drivehome nasce come piattaforma di servizio per i driver. A fronte di una registrazione, Drivehome mette a disposizione dei clienti interessati i driver, mettendoli in contatto secondo lo schema di tutte le piattaforme di sharing e con le modalità che seguono."
                    "Il driver o autista, d’ora in poi “driver” si definisce tale e di conseguenza può avere accesso ai servizi che la piattaforma riserva a questa tipologia di soggetti solo ed unicamente se ha completato il processo di registrazione come segue. In ogni caso l’abilitazione finale è a completa e totale discrezione della piattaforma, senza che la piattaforma stessa abbia alcun obbligo. Altra premessa è che il servizio Autisti Drivehome è rivolto ad entrambi i sessi, ai sensi delle leggi 903/77 e 125/91, e a persone di tutte le età e tutte le nazionalità, ai sensi dei decreti legislativi 215/03 e 216/03. Data la fattispecie del servizio con scrittura in italiano e modalità di comunicazione pubblicitaria sempre in italiano è evidente che la clientela di riferimento è italiana e che costituisce un fattore non discriminante, ma di preferenza la madrelingua italiana o pari livello."
                    "Il driver potrà accedere ai servizi Drivehome specificati  successivamente una volta completata la registrazione come driver sull’ applicazione Autisti Drivehome. La registrazione dei driver parte dalla pagina dell’applicazione a loro dedicata “Registrati come autista”. Si visualizza quindi un form con i seguenti campi da inserire: Nome e Cognome, E-mail (valida come username), Password, N° telefono e in fondo alla pagina il testo informativo : “Registrando un account, accetti i nostri Termini e condizioni e Informativa sulla privacy”. L’autista che avrà compilato il form verrà reindirizzato alla pagina dove obbligatoriamente dovrà caricare front e retro della propria Patente B in corso di validità e della propria Carta d’Identità in corso di validità. Una volta completati questi campi e verificato l’indirizzo email inserito nel form apparirà quindi una finestra pop-up con messaggio “Verifica email. Devi verificare la tua email prima di accedere."
                    "Controlla la tua email”. La mail avrà come oggetto “Benvenuto su Drivehome!” ed all’interno del testo ci sarà il link per attivare l’utenza. Il futuro driver è tenuto, qualora non vedesse la mail a controllare anche la cartella della posta indesiderata. Una volta cliccato sul link si aprirà una pagina web con la voce “Il tuo account è stato attivato” e tornando sull’app avrà quindi portato a termine la Registrazione."
                    "La compilazione inesatta in qualche campo del profilo da parte del driver genera la cancellazione dei dati senza alcun obbligo di comunicazione da parte di Drivehome. Nel caso fosse stata pagata la quota di iscrizione, nessun rimborso sarebbe dovuto e la cifra dell’iscrizione verrebbe fatturata al soggetto come costo di registrazione non avvenuta, ma comunque processata."
                    "È a carico del driver la comunicazione, tassativamente via e-mail, all’indirizzo info@drivehome.it del o degli avvenuti aggiornamenti. La compilazione completa del form di registrazione, il caricamento dei docuementi richiesti e la conferma dell’email registrata, genera un driver abilitato alla pubblicazione, quindi pubblicato sulla piattaforma e alla ricezione delle notifiche push. Nel caso in cui il diver si sia registrato correttamente sarà reindirizzato alla pagina princiaple dell’app Autisti Drivehome dove potrà vedere la propria posizione in tempo reale sulla mappa Google Maps e dove potrà rispondere alle notifiche a comparsa quando un cliente richiederà i suoi servizi da autista privato in prestazione occasionale. Ricevuta una notifica potrà accettare o rifiutare la corsa. Se accetta vedrà disegnarsi su una nuova pagina dell’app una mappa Google con il percorso da percorrere per arrivare dal cliente e mettersi alla guida dell’auto di quest'ultimo. In questa stessa pagina potrà controllare l’itinerario del vaiggio che il cliente vuole compiere con relativo luogo/indirizzo di partenza e luogo/indirizzo di destinazione e due pulsanti con cui annullare la corsa in qualunque momento o comunicare con il cliente. Ad esempio puramente esemplificativo del funzionamento delle due applicazione combinate: quando il driver sarà giunto dal cliente cliccherà sul pulsante “Arrivato” e il cliente vedrà sulla propria applicazione il messaggio “Il tuo autista è arrivato!”, una volta che il driver sarà al volante dell’auto del cliente potrà cliccare il pulsante che nel frattempo sarà cambiato e ora avrà come testo “Andiamo” e potrà partire per il luogo di destinazione indicato. Arrivato alla destinazione cliccherà sul pulsante “Fine Corsa” e vedrà apparire un popup informativo del prezzo ipotizzato di default da Drivehome per il servizio offerto al cliente."
                    "Autisti Drivehome offre un servizio di valutazione dei driver con profilo completo. Questa valutazione è espressa in stelle, partendo da un valore di default di 3 stelle. Il numero di stelle sarà aggiornato in base al numero di recensioni che i clienti lasciano sui servizi erogati dal driver. La valutazione finale è quindi una media delle recensioni ricevute dai clienti sul numero totale dei viaggi effettuati dal driver. "
                    "L’erogazione del servizio o essere un driver abilitato sulla piattaforma Drivehome non dà alcun diritto di utilizzo del logo di Drivehome a nessun titolo. L’utilizzo può avvenire solo a fronte di una domanda circostanziata e viene autorizzato da Drivehome invio a PEC da PEC, dove saranno specificate tutte le condizioni affinchè l’utilizzo avvenga in modo corretto. Drivehome si riserva di inviare ai driver pubblicati e/o non abilitati comunicazioni di servizio riferite per sollecitare il completamento del profilo. Drivehome si riserva anche di inviare a tutti i driver registrati non pubblicati e/o non abilitati le richieste di servizio riferita alla zona geografica stabilita da Drivehome per mettere in contatto i driver con i clienti, senza che questo implichi alcun obbligo di risposta ad eventuali chiarimenti o domande da parte della piattaforma, ma con il solo scopo di esemplificare le opportunità di servizio che la piattaforma può offrire."
                    "Qualora il driver si cancellasse dalla piattaforma, tramite il tasto “cancella il mio account”, non riceverebbe più alcuna richiesta di servizio tramite mail o notifica push. Non è prevista la comunicazione delle richieste di servizio a soggetti che non abbiano acconsentito alla ricezione delle notifiche per l’applicazione Drivehome sul proprio dispositivo smartphone dove l’app risiede e dove si ha effettuato l’accesso all’account. Il guadagno del driver è basato sulla proposta commerciale del cliente che il driver accetta dopo che la corsa è terminata. La piattaforma produce dei preventivi che vanno poi negoziati con i clienti. "
                    "A titolo meramente esemplificativo, se un cliente chiede un servizio che ha bisogno di risposta immediata prevarrà la tempestività con cui i driver danno disponibilità. I criteri di assegnazione ad insindacabile giudizio del cliente che sceglie il driver sulla propria applicazione senza che Drivehome interferisca in nessun modo con la scelta. Qualora nessun driver risponda, questo sarà comunicato al cliente ed il servizio non verrà effettuato."
                    "Dal momento in cui cliente e driver entrano in contatto la relazione è di prestazione occasionale tra privati. A fine servizio se richiesto il driver dovrà produrre ricevuta con ritenuta d’acconto o fattura per l’importo del proprio compenso. Il cliente è quindi responsabile in toto della conformità del proprio mezzo alla guida di terzi. Al driver è consigliato verificare l’assicurazione dell’auto del cliente e le condizioni generali, prima di effettuare il servizio. Qualora ci fossero problemi documentati il driver puo' non effettuare il servizio. Qualora il driver non si presenti Drivehome non ha alcuna responsabilità e non è tenuto ad effettuare alcun rimborso al cliente per danni sopravvenuti per questa causa. Il cliente si deve rivalere adendo a vie legali sul driver. Il driver che non si presenta o si presenta in un ritardo giudicato grave dal cliente viene cancellato immediatamente dalla piattaforma, senza alcuna possibilità di appello ed a prescindere da qualsiasi giustificazione anche documentata possa addurre. Tutto quello che intercorre dal momento in cui cliente e driver ricevono i reciproci contatti riguarda solo ed esclusivamente cliente e driver. In nessun caso ci si può rivalere sulla piattaforma."
                    "Nessuna delle due parti può ritenere l'altra responsabile per eventuali danni o perdite causati da eventi imprevisti, come ad esempio il maltempo o la mancata accettazione della richiesta da parte del driver.Le presenti Condizioni Generali sono disciplinate e regolate dalla legge italiana. Per la soluzione di controversie relative all’interpretazione, esecuzione o risoluzione delle presenti Termini e Condizioni il Foro di Bari avrà competenza esclusiva.",
                style : TextStyle(
                  fontSize: 17,
                  color: Colors.white,
                  fontWeight: FontWeight.normal,
                ),
              ),



            ],
          ),
        ),
      ),
    );
  }
}
